# Generated by Django 4.2.4 on 2026-05-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_waiter_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('waiter', 'Waiter'), ('kitchen', 'Kitchen'), ('cashier', 'Cashier')], max_length=20),
        ),
    ]
