# Generated by Django 4.2.4 on 2026-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_stock_deducted_recipecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
