# Generated by Django 4.2.4 on 2026-05-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_menuitem_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_path',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, upload_to='menu_items/'),
        ),
    ]
