# Generated by Django 4.2.4 on 2026-05-09 21:43

from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_purchase_rows(apps, schema_editor):
    Purchase = apps.get_model('restaurant', 'Purchase')
    PurchaseItem = apps.get_model('restaurant', 'PurchaseItem')
    for purchase in Purchase.objects.all().iterator():
        if purchase.inventory_item_id is None or purchase.quantity is None:
            continue
        PurchaseItem.objects.create(
            purchase_id=purchase.id,
            inventory_item_id=purchase.inventory_item_id,
            quantity=purchase.quantity,
            unit_cost=purchase.unit_cost,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_supplier_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='restaurant.inventoryitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.purchase')),
            ],
            options={
                'ordering': ['inventory_item__name'],
            },
        ),
        migrations.RunPython(forwards_copy_purchase_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='purchase',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unit_cost',
        ),
    ]
