# Generated by Django 4.2.4 on 2026-05-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_purchase_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
