# Generated by Django 4.2.4 on 2026-05-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_purchase_purchase_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='plu',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
