# Generated by Django 4.2.4 on 2026-05-10 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0011_cashdeskentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('barcode_scan', 'Barcode scan')], max_length=30)),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=9)),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=9)),
                ('barcode', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_history_entries', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='restaurant.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
