# Generated by Django 4.2.4 on 2026-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_inventoryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='source',
            field=models.CharField(choices=[('barcode_scan', 'Barcode scan'), ('purchase', 'Purchase'), ('recipe_order', 'Order recipe')], max_length=30),
        ),
    ]
