# Generated by Django 4.2.4 on 2026-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_inventoryhistory_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='source',
            field=models.CharField(choices=[('barcode_scan', 'Scale barcode scan'), ('purchase', 'Purchase'), ('recipe_order', 'Order recipe')], max_length=30),
        ),
    ]
