# Generated by Django 4.2.4 on 2026-05-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_inventoryhistory_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashdeskentry',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='quantity_after',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='quantity_before',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='quantity_change',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Scalbarcodescan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=32, unique=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcode_scans', to='restaurant.inventoryitem')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
