# Generated by Django 4.2.4 on 2026-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_purchase_total_purchaseitem_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalbarcodescan',
            name='barcode',
            field=models.CharField(max_length=32),
        ),
    ]
