# Generated by Django 4.2.4 on 2026-05-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_scalbarcodescan_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashdeskentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='inventoryhistory',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='scalbarcodescan',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='cashdeskentry',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='inventoryhistory',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='scalbarcodescan',
            old_name='scanned_at',
            new_name='date',
        ),
    ]
